# Generated by Django 3.1.4 on 2021-03-01 17:20

from django.db import migrations, models
import user.enums


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='subscription',
            field=models.CharField(choices=[(user.enums.Subscription['BASE'], '20 swipes per day, 10 km'), (user.enums.Subscription['VIP'], '100 swipes per day, 25 km'), (user.enums.Subscription['PREMIUM'], 'unlimited swipes, dynamic km')], default='BASE', max_length=50),
        ),
    ]
