# Generated by Django 3.1.4 on 2021-03-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210301_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='subscription',
            field=models.CharField(choices=[('20 swipes per day, 10 km', 'Base'), ('100 swipes per day, 25 km', 'Vip'), ('unlimited swipes, dynamic km', 'Premium')], default='BASE', max_length=50),
        ),
    ]
